### ISSUE TITLE
How can i run CrossCraft on linux?

### ISSUE THREAD

**Issue by Unpibe10** [CrossCraft/CrossCraft-Classic#77]
I have a problem which is that when decompressing the download file and opening the files directory in the terminal and executing "Crosscraft-Classic" It gives me an Open GL error and the initialized base layer. I don't understand very well what's going on

**Comment by BCDeshiG** [comment]
Sounds quite similar to #75 , try checking what they did.

**Comment by IridescentRose** [comment]
Sounds like your OpenGL is out of date as well. Can you give me an OS name and version?

**Comment by Unpibe10** [comment]
> 

Is Linux Mint 21

**Comment by SpidFightFR** [comment]
@Unpibe10 the mesa drivers on linux that include OpenGL, are compatible with the 4.0 version of OpenGL required for the game to run.

However, since this version of OpenGL is considered unstable, the default version is OpenGL 3.0. In this issue #75 i explain how to fix this issue. You can either add environment variables in /etc/environment (i won’t recommend this) or you can launch the game with the command i written in the issue (the way i recommend).

i hope it helped you.
